### ISSUE TITLE
Image zoom in center

### ISSUE THREAD

**Issue by mohsinalimat** [twomedia/TMImageZoom#1]
Hello,

your code is help me and in your class image zoom in center of image center point but i want to zoom in when user touch any angle then zoom start from that area.

Thanks,
Mohsinali Matiya

**Comment by twomedia** [comment]
Hi @mohsinalimat 

This stackoverflow answer explains exactly what you are after:
http://stackoverflow.com/questions/25859069/using-pinchgesture-how-can-i-zoom-in-to-where-a-users-fingers-actually-pinch

Let me know if you have any issues :)

**Comment by mohsinalimat** [comment]
i did zoom in features like as instagram

- (void)btnActionToPinchGesture:(UIPinchGestureRecognizer *)recognizer
{
    UIGestureRecognizerState state = [recognizer state];
    
    if (state == UIGestureRecognizerStateBegan || state == UIGestureRecognizerStateChanged)
    {
        
        UIView *pinchView = recognizer.view;
        CGRect bounds = pinchView.bounds;
        CGPoint pinchCenter = [recognizer locationInView:pinchView];
        pinchCenter.x -= CGRectGetMidX(bounds);
        pinchCenter.y -= CGRectGetMidY(bounds);
        CGAffineTransform transform = pinchView.transform;
        transform = CGAffineTransformTranslate(transform, pinchCenter.x, pinchCenter.y);
        CGFloat scale = recognizer.scale;
        transform = CGAffineTransformScale(transform, scale, scale);
        transform = CGAffineTransformTranslate(transform, -pinchCenter.x, -pinchCenter.y);
        if (transform.a > 1 && transform.d > 1) {
            pinchView.transform = transform;
        }
        
        recognizer.scale = 1.0;
    }
    
    if (state == UIGestureRecognizerStateEnded){
        
        [UIView transitionWithView: recognizer.view duration:0.2
                           options:UIViewAnimationOptionCurveEaseIn
                        animations:^{
                            CGAffineTransform transform = recognizer.view.transform;
                            transform.a = 1.0;
                            transform.d = 1.0;
                            transform.tx = 0;
                            transform.ty = 0;
                            recognizer.view.transform = transform;
                            recognizer.scale = 1.0;
                        }
                        completion:nil];
        
    }
}
