### ISSUE TITLE
[QUESTION] : How to use TMImageZoom for multiple images in scroll view

### ISSUE THREAD

**Issue by asshewale** [twomedia/TMImageZoom#3]
Hi I really loved the way TMImageZoom works, 

Actually i do have multiple scrolling images in scrollview with horizontal scrolling, and i want to give the zoomin zoomout effect to each image in scrollview...

The method : `- (void)pinch:(UIPinchGestureRecognizer *)gesture {
    
    [[TMImageZoom shared] gestureStateChanged:gesture withZoomImageView:imageView];
}`

above method do need a parameter uiimageview , in my case the different imageViews are already added in scrollview so how should i use TMImageZoom for all those imageViews inside the scroll view

your any help will be highly appreciated.

**Comment by twomedia** [comment]
Sorry for the late reply on this! Didn't see it until now...

So basically all you need to do is add a pinch gesture recogniser to each image and then on the gesture state changes call the method you posted above and pass in the imageView.

**Comment by twomedia** [comment]
If you have any other questions let me know... I've fixed up my notification settings so I'll see it this time!
